
<template>
  <div>
    <div class="loadingio-spinner-rolling-shizuxicb6"><div class="ldio-7gzw0g0zu9h">
<div></div>
</div></div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-7gzw0g0zu9h {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-7gzw0g0zu9h div {
  position: absolute;
  width: 120px;
  height: 120px;
  border: 20px solid #e15b64;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-7gzw0g0zu9h div {
  animation: ldio-7gzw0g0zu9h 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-shizuxicb6 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-7gzw0g0zu9h {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-7gzw0g0zu9h div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
