<template>
  <div class="wrap-loading">
    <div class="loading-box">
      <div class="loading-content">
        <div></div>
      </div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes loading-content {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.wrap-loading {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(82, 77, 76, .5);
}
.loading-content div {
  position: absolute;
  width: 40px;
  height: 40px;
  border: 10px solid #e15b64;
  border-top-color: transparent;
  border-radius: 50%;
}
.loading-content div {
  animation: loading-content 1s linear infinite;
  top: 100px;
  left: 100px;
}
.loading-box {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
    position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);

}
.loading-content {
  width: 100%;
  height: 100%;

  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.loading-content div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
